version: '3.4'

services:
  web:
    image: nginxinc/nginx-unprivileged:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
#    image: php:fpm-alpine
    build: .
    volumes:
      - ./src:/src
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  db:
    image: postgres:12-alpine
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
